spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://locushaunt-mysql.cts5zbx6unos.ap-south-1.rds.amazonaws.com:3306/zack-apps
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ZACK-APPS-TECHNICAL

zack:
  app:
    jwtSecret: HP5CfKVoRuLGfIIU9iUAr2Flpp15ijtEJMRAHB4mYlsoRGhYHsiqR12qhGsoXuHI
    jwtExpirationMs: 86400000